### ISSUE TITLE
Vis is not working on Safari macOSX and iOS with activated proxy adapter

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.proxy#10]
Stucks at connecting to server and is refreshing:
WebSocket connection to 'ws://192.168.178.x:8080/socket.io/?key=nokey&EIO=3&transport=websocket&sid=S8Rts8kacaLjsefdAAAc' failed: Compressed bit must be 0 if no negotiated deflate-frame extension

**Comment by TA2k** [comment]
Issue is only with http and when an image is included in the vis.
Direct url to image is working without problems
Https proxy path is also working without problems

**Comment by GermanBluefox** [comment]
This is known Problem that does not have a valid solution. Only workarounds:
- Enable "Use simple proxy"
- Use extra socket.io instance, that is not built in into web instance
