### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.proxy#100]
I configured proxying of a local file 

![image](https://user-images.githubusercontent.com/29343914/184326108-516254f0-7227-44dc-85b5-437f543f6255.png)

like that

![image](https://user-images.githubusercontent.com/29343914/184323610-50ba781a-51a4-4255-8150-6644e980e9a0.png)

but I get 

![image](https://user-images.githubusercontent.com/29343914/184324253-14bf2a68-6b91-49e6-9b29-18028917d18b.png)

`[proxy] File "/volume1/public/loader.gif/" not found.`

there is a trailing `/` 
Could this be the problem?

**Comment by EvilEls** [comment]
quick fix
`/opt/iobroker/node_modules/iobroker.proxy/lib/proxy.js`

add
`fileName = fileName.replace(/\/$/g, '');`

after line 221
`let fileName = rule.url + req.url;`

**Comment by Apollon77** [comment]
This will work exactly for your one cae, but if someone requests a directly it will break ... I will try something

**Comment by Apollon77** [comment]
Can you please prvide a debug log of sucha call?

**Comment by Apollon77** [comment]
Please check GitHub version

**Comment by EvilEls** [comment]
GitHub version is working.
Thank you! 👍
