### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.proxy#12]
![grafik](https://user-images.githubusercontent.com/6681528/76139633-420db200-6052-11ea-8b20-be31a54368b8.png)

web is https
my grafana works with http

other error is here
![grafik](https://user-images.githubusercontent.com/6681528/76139675-d6781480-6052-11ea-9405-42bb0d6deed3.png)
with simple image

**Comment by Apollon77** [comment]
To add more infos from research:
We checked debug log and it seems that the requests that are mentioned here were successfully delivered and also the finishRequest logic found the entry (tested both searching for res and req) and so removed it. We also checkd if the same entry is twice in the array. Also not the case.

So in fact very strange. It seems there is still a request entry in the array even after the response was delivered correctly

Arteck used the real proxy (not simple proxy)

**Comment by GermanBluefox** [comment]
What the error timeout is configured?
