### ISSUE TITLE
Pfade zu Dateien funktionieren nicht

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.proxy#19]
Hallo,

ich habe das Problem, dass Pfade die auf Dateien zeigen nicht funktionieren.

Es kommt der Fehler:
`[proxy] File "/opt/iobroker/download/bild.jpg/" not found.`

Eingestellt habe ich alles laut readme.
Wenn ich auf einen Ordner verweise klappt es. 
Wenn man dort allerdings auf eine Datei klickt kommt der selbe Fehler. 

[Hier](https://forum.iobroker.net/topic/43440/konfiguration-proxy-adapter) habe ich es schonmal im ioBroker Forum angesprochen.

**Comment by Apollon77** [comment]
Lösung am besten im Forum,

**Comment by Apollon77** [comment]
Ok, mehr detaills hoer wären echt hilfreich gewesen.

Kontext: bild.jpg
URL: /pfad/zum/bild.jpg

ergibt [proxy] File "/opt/iobroker/download/bild.jpg/" not found.

**Comment by ipod86** [comment]
Sorry, da hast du recht.
War was sperrlich.

Okay, weiter im Forum.

**Comment by Apollon77** [comment]
see Forum, please try GitHub version and provide logs
