### ISSUE TITLE
can not connect file to proxy.0

### ISSUE THREAD

**Issue by MarioP73** [ioBroker/ioBroker.proxy#3]
I want the MP3 file
/opt/iobroker/node_modules/iobroker.sayit/say.mp3
via the proxy adapter. So far without success.

**Context:**
say.mp3

**URL:**
/node_modules/iobroker.sayit/say.mp3

**time out:**
1000

Where is my mistake? Who can help me here.

**Comment by GermanBluefox** [comment]
URL => /opt/iobroker/node_modules/iobroker.sayit/say.mp3
?

**Comment by GermanBluefox** [comment]
Or URL: http://ip:8082/state/sayit.0.tts.mp3

**Comment by MarioP73** [comment]
URL: http://ip:8082/state/sayit.0.tts.mp3
---->
{"type":"Buffer","data":[255,243,68,196,0,17,248,94,28,0,121,134,40,17,160,52, .................

no mp3-file return vom browser


URL => /opt/iobroker/node_modules/iobroker.sayit/say.mp3

no return vom browser

**Comment by GermanBluefox** [comment]
No more info. Closed.
