### ISSUE TITLE
can't add path

### ISSUE THREAD

**Issue by CBMOD** [ioBroker/ioBroker.proxy#4]
when i click on "+" nothing does

**Comment by CBMOD** [comment]
ioBroker Admin V3.2.0
Proxy V1.0.1
![iobroker_proxy](https://user-images.githubusercontent.com/36811706/39929545-9a8f05ae-5538-11e8-8371-9ab84ee0118b.PNG)
![iobroker_proxy1](https://user-images.githubusercontent.com/36811706/39929559-a236c06c-5538-11e8-8e23-4f640b9f2756.PNG)

**Comment by Apollon77** [comment]
Please update to a ore current Admin (3.4.2 is current I think) ... then retry please

**Comment by CBMOD** [comment]
that's it - work's with Admin V3.4.2
problem solved

**Comment by GermanBluefox** [comment]
Please update admin to 3.4.2 or downgrade to 2.0.9

пт, 11 мая 2018 г., 16:30 CBMOD <notifications@github.com>:
